name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: prep
        run: |
          echo ::set-output name=version::$(jq .version -r package.json)
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.prep.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: prep
        run: |
          echo ::set-output name=version::$(jq .version -r package.json)
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/skolorna/opengraph:${{ steps.prep.outputs.version }}
            ghcr.io/skolorna/opengraph:latest
